trigger:
- 'try1'

stages:
- stage: 'Stage1'
  displayName : 'Test stage'
  jobs :
  - job : 'job1'
    displayName : 'job1'
    
    steps :
     - task : CmdLine@2
       inputs:
        script: 'echo HEllO WORLDWA' 

  - job : 'job2'
    displayName : 'job2'
    
    steps :
     - task : CmdLine@2
       inputs:
        script: 'echo HEllO WORLDWA' 
